---@alias Element
---| '"Thunder"'
---| '"Ice"'
---| '"Fire"'
---| '"Wind"'
---| '"Water"'
---| '"Earth"'
---| '"Dark"'
---| '"Light"'

---@alias Skillchain
---| '"Light"'
---| '"Darkness"'
---| '"Gravitation"'
---| '"Fragmentation"'
---| '"Distortion"'
---| '"Fusion"'
---| '"Compression"'
---| '"Liquefaction"'
---| '"Induration"'
---| '"Reverberation"'
---| '"Transfixion"'
---| '"Scission"'
---| '"Detonation"'
---| '"Impaction"'
---| '"Radiance"'
---| '"Umbra"'

-- https://www.bg-wiki.com/ffxi/Category:Bestiary
---@alias CreatureFamily
---| '"Beast"'
---| '"Lizard"'
---| '"Vermin"'
---| '"Plantoid"'
---| '"Amorph"'
---| '"Bird"'
---| '"Aquan"'
---| '"Undead"'
---| '"Arcana"'
---| '"Dragon"'
---| '"Demon"'
---| '"Blessed Races of Altana"' Playable races
---| '"Beastmen"'
---| '"Empty"'
---| '"Luminian"'
---| '"Luminion"'
---| '"Vorageans"'
---| '"Archaic Machine"'
---| '"Elemental"'
---| '"Structure"'
---| '"Unclassified"'

---@alias PhysicalDamageType
---| '"Blunt"'
---| '"Piercing"'
---| '"Slashing"'

---@alias GearSlot
---| '"Main"'
---| '"Sub"'
---| '"Range"'
---| '"Ammo"'
---| '"Head"'
---| '"Neck"'
---| '"Ear1"'
---| '"Ear2"'
---| '"Body"'
---| '"Hands"'
---| '"Ring1"'
---| '"Ring2"'
---| '"Back"'
---| '"Waist"'
---| '"Legs"'
---| '"Feet"'

---@class (exact) GearSet
---@field Main string?
---@field Sub string?
---@field Range string?
---@field Ammo string?
---@field Head string?
---@field Neck string?
---@field Ear1 string?
---@field Ear2 string?
---@field Body string?
---@field Hands string?
---@field Ring1 string?
---@field Ring2 string?
---@field Back string?
---@field Waist string?
---@field Legs string?
---@field Feet string?

---@class (exact) PriorityGearSet
---@field Main string[]?
---@field Sub string[]?
---@field Range string[]?
---@field Ammo string[]?
---@field Head string[]?
---@field Neck string[]?
---@field Ear1 string[]?
---@field Ear2 string[]?
---@field Body string[]?
---@field Hands string[]?
---@field Ring1 string[]?
---@field Ring2 string[]?
---@field Back string[]?
---@field Waist string[]?
---@field Legs string[]?
---@field Feet string[]?
